# Generated by Django 5.0.4 on 2024-04-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_collection_slug_collection_slug_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='slug_field',
        ),
    ]
