# Generated by Django 5.0.4 on 2024-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_collection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_field',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
