# Generated by Django 5.0.4 on 2024-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_first_n_a7e990_idx',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['given_name', 'last_name'], name='store_custo_given_n_1a7060_idx'),
        ),
    ]
