# Generated by Django 5.0.4 on 2024-04-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_collection_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
        migrations.AddField(
            model_name='collection',
            name='slug_field',
            field=models.SlugField(default='default_slug', null=True),
        ),
    ]
